/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IpoRouteImport } from './routes/ipo'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as IndiaRouteImport } from './routes/india'
import { Route as GrowthSystemRouteImport } from './routes/growth-system'
import { Route as FreeAuditRouteImport } from './routes/free-audit'
import { Route as ErpRouteImport } from './routes/erp'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesSaudiAramcoRouteImport } from './routes/case-studies.saudi-aramco'
import { Route as CaseStudiesOmSteelRouteImport } from './routes/case-studies.om-steel'
import { Route as CaseStudiesKuberRouteImport } from './routes/case-studies.kuber'
import { Route as CaseStudiesErpUnifiedSystemRouteImport } from './routes/case-studies.erp-unified-system'
import { Route as CaseStudiesErpMarginRecoveryRouteImport } from './routes/case-studies.erp-margin-recovery'
import { Route as CaseStudies25CroreRfqRouteImport } from './routes/case-studies.25-crore-rfq'

const IpoRoute = IpoRouteImport.update({
  id: '/ipo',
  path: '/ipo',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiaRoute = IndiaRouteImport.update({
  id: '/india',
  path: '/india',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthSystemRoute = GrowthSystemRouteImport.update({
  id: '/growth-system',
  path: '/growth-system',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeAuditRoute = FreeAuditRouteImport.update({
  id: '/free-audit',
  path: '/free-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpRoute = ErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSaudiAramcoRoute = CaseStudiesSaudiAramcoRouteImport.update({
  id: '/case-studies/saudi-aramco',
  path: '/case-studies/saudi-aramco',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesOmSteelRoute = CaseStudiesOmSteelRouteImport.update({
  id: '/case-studies/om-steel',
  path: '/case-studies/om-steel',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesKuberRoute = CaseStudiesKuberRouteImport.update({
  id: '/case-studies/kuber',
  path: '/case-studies/kuber',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesErpUnifiedSystemRoute =
  CaseStudiesErpUnifiedSystemRouteImport.update({
    id: '/case-studies/erp-unified-system',
    path: '/case-studies/erp-unified-system',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudiesErpMarginRecoveryRoute =
  CaseStudiesErpMarginRecoveryRouteImport.update({
    id: '/case-studies/erp-margin-recovery',
    path: '/case-studies/erp-margin-recovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudies25CroreRfqRoute = CaseStudies25CroreRfqRouteImport.update({
  id: '/case-studies/25-crore-rfq',
  path: '/case-studies/25-crore-rfq',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/erp': typeof ErpRoute
  '/free-audit': typeof FreeAuditRoute
  '/growth-system': typeof GrowthSystemRoute
  '/india': typeof IndiaRoute
  '/international': typeof InternationalRoute
  '/ipo': typeof IpoRoute
  '/case-studies/25-crore-rfq': typeof CaseStudies25CroreRfqRoute
  '/case-studies/erp-margin-recovery': typeof CaseStudiesErpMarginRecoveryRoute
  '/case-studies/erp-unified-system': typeof CaseStudiesErpUnifiedSystemRoute
  '/case-studies/kuber': typeof CaseStudiesKuberRoute
  '/case-studies/om-steel': typeof CaseStudiesOmSteelRoute
  '/case-studies/saudi-aramco': typeof CaseStudiesSaudiAramcoRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/erp': typeof ErpRoute
  '/free-audit': typeof FreeAuditRoute
  '/growth-system': typeof GrowthSystemRoute
  '/india': typeof IndiaRoute
  '/international': typeof InternationalRoute
  '/ipo': typeof IpoRoute
  '/case-studies/25-crore-rfq': typeof CaseStudies25CroreRfqRoute
  '/case-studies/erp-margin-recovery': typeof CaseStudiesErpMarginRecoveryRoute
  '/case-studies/erp-unified-system': typeof CaseStudiesErpUnifiedSystemRoute
  '/case-studies/kuber': typeof CaseStudiesKuberRoute
  '/case-studies/om-steel': typeof CaseStudiesOmSteelRoute
  '/case-studies/saudi-aramco': typeof CaseStudiesSaudiAramcoRoute
  '/case-studies': typeof CaseStudiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/erp': typeof ErpRoute
  '/free-audit': typeof FreeAuditRoute
  '/growth-system': typeof GrowthSystemRoute
  '/india': typeof IndiaRoute
  '/international': typeof InternationalRoute
  '/ipo': typeof IpoRoute
  '/case-studies/25-crore-rfq': typeof CaseStudies25CroreRfqRoute
  '/case-studies/erp-margin-recovery': typeof CaseStudiesErpMarginRecoveryRoute
  '/case-studies/erp-unified-system': typeof CaseStudiesErpUnifiedSystemRoute
  '/case-studies/kuber': typeof CaseStudiesKuberRoute
  '/case-studies/om-steel': typeof CaseStudiesOmSteelRoute
  '/case-studies/saudi-aramco': typeof CaseStudiesSaudiAramcoRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/erp'
    | '/free-audit'
    | '/growth-system'
    | '/india'
    | '/international'
    | '/ipo'
    | '/case-studies/25-crore-rfq'
    | '/case-studies/erp-margin-recovery'
    | '/case-studies/erp-unified-system'
    | '/case-studies/kuber'
    | '/case-studies/om-steel'
    | '/case-studies/saudi-aramco'
    | '/case-studies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/erp'
    | '/free-audit'
    | '/growth-system'
    | '/india'
    | '/international'
    | '/ipo'
    | '/case-studies/25-crore-rfq'
    | '/case-studies/erp-margin-recovery'
    | '/case-studies/erp-unified-system'
    | '/case-studies/kuber'
    | '/case-studies/om-steel'
    | '/case-studies/saudi-aramco'
    | '/case-studies'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/erp'
    | '/free-audit'
    | '/growth-system'
    | '/india'
    | '/international'
    | '/ipo'
    | '/case-studies/25-crore-rfq'
    | '/case-studies/erp-margin-recovery'
    | '/case-studies/erp-unified-system'
    | '/case-studies/kuber'
    | '/case-studies/om-steel'
    | '/case-studies/saudi-aramco'
    | '/case-studies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ErpRoute: typeof ErpRoute
  FreeAuditRoute: typeof FreeAuditRoute
  GrowthSystemRoute: typeof GrowthSystemRoute
  IndiaRoute: typeof IndiaRoute
  InternationalRoute: typeof InternationalRoute
  IpoRoute: typeof IpoRoute
  CaseStudies25CroreRfqRoute: typeof CaseStudies25CroreRfqRoute
  CaseStudiesErpMarginRecoveryRoute: typeof CaseStudiesErpMarginRecoveryRoute
  CaseStudiesErpUnifiedSystemRoute: typeof CaseStudiesErpUnifiedSystemRoute
  CaseStudiesKuberRoute: typeof CaseStudiesKuberRoute
  CaseStudiesOmSteelRoute: typeof CaseStudiesOmSteelRoute
  CaseStudiesSaudiAramcoRoute: typeof CaseStudiesSaudiAramcoRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ipo': {
      id: '/ipo'
      path: '/ipo'
      fullPath: '/ipo'
      preLoaderRoute: typeof IpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/india': {
      id: '/india'
      path: '/india'
      fullPath: '/india'
      preLoaderRoute: typeof IndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-system': {
      id: '/growth-system'
      path: '/growth-system'
      fullPath: '/growth-system'
      preLoaderRoute: typeof GrowthSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-audit': {
      id: '/free-audit'
      path: '/free-audit'
      fullPath: '/free-audit'
      preLoaderRoute: typeof FreeAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erp': {
      id: '/erp'
      path: '/erp'
      fullPath: '/erp'
      preLoaderRoute: typeof ErpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/saudi-aramco': {
      id: '/case-studies/saudi-aramco'
      path: '/case-studies/saudi-aramco'
      fullPath: '/case-studies/saudi-aramco'
      preLoaderRoute: typeof CaseStudiesSaudiAramcoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/om-steel': {
      id: '/case-studies/om-steel'
      path: '/case-studies/om-steel'
      fullPath: '/case-studies/om-steel'
      preLoaderRoute: typeof CaseStudiesOmSteelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/kuber': {
      id: '/case-studies/kuber'
      path: '/case-studies/kuber'
      fullPath: '/case-studies/kuber'
      preLoaderRoute: typeof CaseStudiesKuberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/erp-unified-system': {
      id: '/case-studies/erp-unified-system'
      path: '/case-studies/erp-unified-system'
      fullPath: '/case-studies/erp-unified-system'
      preLoaderRoute: typeof CaseStudiesErpUnifiedSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/erp-margin-recovery': {
      id: '/case-studies/erp-margin-recovery'
      path: '/case-studies/erp-margin-recovery'
      fullPath: '/case-studies/erp-margin-recovery'
      preLoaderRoute: typeof CaseStudiesErpMarginRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/25-crore-rfq': {
      id: '/case-studies/25-crore-rfq'
      path: '/case-studies/25-crore-rfq'
      fullPath: '/case-studies/25-crore-rfq'
      preLoaderRoute: typeof CaseStudies25CroreRfqRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ErpRoute: ErpRoute,
  FreeAuditRoute: FreeAuditRoute,
  GrowthSystemRoute: GrowthSystemRoute,
  IndiaRoute: IndiaRoute,
  InternationalRoute: InternationalRoute,
  IpoRoute: IpoRoute,
  CaseStudies25CroreRfqRoute: CaseStudies25CroreRfqRoute,
  CaseStudiesErpMarginRecoveryRoute: CaseStudiesErpMarginRecoveryRoute,
  CaseStudiesErpUnifiedSystemRoute: CaseStudiesErpUnifiedSystemRoute,
  CaseStudiesKuberRoute: CaseStudiesKuberRoute,
  CaseStudiesOmSteelRoute: CaseStudiesOmSteelRoute,
  CaseStudiesSaudiAramcoRoute: CaseStudiesSaudiAramcoRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
